### ISSUE TITLE
SMTPServerDisconnected error with send_mail and Celery

### ISSUE THREAD

**Issue by mihalikv** [ui/django-post_office#218]
Hello, i am facing issue when i want to send_mail like this:
```
@task(name='send_registration_mail')
def send_registration_mail():
    # some stuff
    mail.send(
	    subject=template.subject,
	    message=message,
	    html_message=rendered_content,
	    priority='now'
	    **kwargs
	)
```
This code mostly ends failed with `SMTPServerDisconnected` in log '**please run connect() first**'. When i manualy requeue emails via admin and run `send_queued_mail`, emails are send.

dependencies:
```
django-post-office==3.0.3
Django==1.10.7

celery = 4.0.2
```

**Comment by VerosK** [comment]
Hi, @mihalikv  I have similar issues on one machine of two deployed (both Celery 3.x, Django 1.10, PostOffice 3.0.4).  

Can you provide more details on your configration? I'm interested which Django mail backend and which MTA are you using.

**Comment by yprez** [comment]
I'm getting the same problem... seems like an older issue that I missed.

It also happens in the shell, when leaving it open for long.

**Comment by mihalikv** [comment]
@VerosK we use 
`EMAIL_POST_OFFICE_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'` and Microsoft Office.

Current set up is using `send_mail ` without celery task and created scheduled Celery task every minute like this:

```
@app.task(name='send_queued_mail')
def send_queued_mail():
    call_command('send_queued_mail')
```
with following settings:

```
POST_OFFICE = {
    'DEFAULT_PRIORITY': 'high'
}
```
we also have following celery task to send failed emails every 2 minutes:

```
@app.task(name='send_failed_mails')
def send_failed_mails():
    from post_office.models import Email, STATUS, Log

    max_retries = getattr(settings, 'EMAIL_MAX_RETRIES', 5)
    # select FAILED email WHERE num_logs <= max
    query_set = Email.objects.annotate(num_logs=Count('logs')).filter(Q(status__isnull=True) | Q(status=STATUS.failed)).filter(num_logs__lte=max_retries).all()
    logs = []
    for mail in query_set:
        if not mail.status:
            logger.error('Email without status with id: {} from: {}, to: {}'.format(mail.id, mail.from_email, mail.to))
        if mail.logs.count() == max_retries:
            logger.error('Unable to send mail with id: {} from: {}, to: {}'.format(mail.id, mail.from_email, mail.to))
            # here we create new log to stop sending over and over
            logs.append(Log(email=mail, status=STATUS.failed, message='maximum retries exceeded', exception_type='maximum retries exceeded'))
        else:
            mail.status = STATUS.queued
        mail.save()
    Log.objects.bulk_create(logs)
```

I also facing to issue with `'DEFAULT_PRIORITY': 'now'` some emails ends up with status `None`. Reason was probably that when you don't have setting `EMAIL_TIMEOUT`, email is created but it takes to long and wsgi kill process and you end with email with status `None`.

**Comment by shtalinberg** [comment]
I'm getting the same problem with Ubuntu VestaCP+Exim
After few success sending I get SMTPSenderRefused  (421, b'do1.rionta.com: SMTP command timeout - closing connection', <my_email_from>) and others emails 'failed' with SMTPServerDisconnected  please run connect() first
See logs  https://c2n.me/3SNkiDI.png

When i manualy requeue emails via admin and run send_queued_mail, emails are send.

```
Django==2.0.3
django-post_office==3.0.4
celery==4.1.0
```

`EMAIL_BACKEND = 'post_office.EmailBackend'`
also I try set
```
EMAIL_TIMEOUT = 10
POST_OFFICE = {
    'DEFAULT_PRIORITY': 'now'
}
```
but it's didn't help

**Comment by shtalinberg** [comment]
now I try add snipped from README.rst file to the project's wsgi.py file instead cron but also getting the same problem

**Comment by shtalinberg** [comment]
It seems that the problem in the version of Python
We up version from Python 3.5.2 (default Ubuntu 16.04)  to Python 3.6.4 and problem is gone.

**Comment by cberzan** [comment]
I'm seeing the same problem with post_office 3.0.4, Django 1.11.10, without using Celery at all. Sending emails from the shell starts failing after a while, with "Server not connected" and "please run connect() first" in the post_office logs. In the postfix logs, I see "timeout after END-OF-MESSAGE" as mentioned in a previous comment.

Looking through the code, I suspect the connection cache (connections.py) is to blame. Suppose we start with an empty cache, and we send an email with `mail.send(..., priority='now')`. That would cause a connection to be opened [here](https://github.com/ui/django-post_office/blob/62aa4aa516e9ae87d700fb4dee43c473aceb7434/post_office/connections.py#L32), but then it seems like we never close that connection. After 5 minutes, postfix says "timeout after END-OF-MESSAGE" and closes our connection. If we try to send an email after that, we will reuse the stale connection from the cache, which results in a "Server not connected" / "please run connect() first" error.

@yprez and other contributors, can you confirm that this is the issue? And if so, what's the best way to fix it?

**Comment by shtalinberg** [comment]
what version of python do you use?

**Comment by yprez** [comment]
@cberzan yep, that was the issue for me. post_office 3.0.3, python 3.5 (don't remember the exact version). Every long running process would lose connection to smtp at some point.

I had post_office in one active project that didn't really require it, so I replaced it with custom rendering code instead of looking for the bug.

**Comment by ambhar** [comment]
This problem still seems to be there. Did anyone find any fixes?
Mails fail with status "SMTPServerDisconnected" and messages "Connection unexpectedly closed" or "please run connect() first".
A reboot of the server is required to send emails again, but it doesn't last for much time and start giving errors again.
Thanks

**Comment by shtalinberg** [comment]
Try just up Python version

**Comment by amiraliakbari** [comment]
Looking at the library code, it seem that when using `now` priority, the connection to smtp server is not closed. But when using the management command, there is a [line](https://github.com/ui/django-post_office/blob/master/post_office/mail.py#L266) saying `connections.close()` after sending all pending emails. To fix this issue, I suggest closing the used connection after sending any email with `now` priority, at the [end of](https://github.com/ui/django-post_office/blob/master/post_office/models.py#L151) `Email.dispatch` method, when commit is True.

**Comment by grapo** [comment]
Like @cberzan wrote, it's because of connection cache and smtp timeouts. I have some dirty hack that fixes this issue for me. I'm using it with `django.core.mail.backends.smtp.EmailBackend`
```python
from post_office.connections import connections

connections._connections.connections['default'].close()  # because it might be opened and we can't check
connections._connections.connections['default'].open()
# actual code for sending messages
...

connections._connections.connections['default'].close()
```

Proper solution is IMO add option to disable connection caching when using long running threads.

**Comment by tderouin** [comment]
```
from post_office.connections import connections
....
connections._connections.connections['default'].close()
```

Error:

```
thread._local has no attribute 'connections'

**Comment by Brandl** [comment]
Same problem, probably because this is running in a production enviroment with multiple gunicorn threads?

```
line 96, in send_email
connections._connections.connections['default'].close()  # because it might be opened and we can't check
AttributeError: '_thread._local' object has no attribute 'connections'
```

Is there any clean workaround to disable connection caching? ( #228 )

**Comment by grapo** [comment]
I changed it later, works on production without problems:
```python    
try:
    connections._connections.connections['default'].close()
    connections._connections.connections['default'].open()
except AttributeError:
    pass
```
Don't judge me :)

I will try to find some time to make pull request with disabling connection caching based on settings. It will solve all of the problems.

**Comment by xiez** [comment]
How about just close the connection after sending email with priority NOW ? 

As in https://github.com/haiwen/django-post_office/commit/2312cf240363721f737b5ac8eb86ab8cb255938f

**Comment by markusmo** [comment]
is there an update to this issue?
Or do I simply not use `now` as a priority?

**Comment by keto** [comment]
Seems that the Email.dispatch() method used to close the connection, but that changed in commit 03d1a37 and now the connection times out.

**Comment by erh94** [comment]
> Like @cberzan wrote, it's because of connection cache and smtp timeouts. I have some dirty hack that fixes this issue for me. I'm using it with `django.core.mail.backends.smtp.EmailBackend`
> 
> ```python
> from post_office.connections import connections
> 
> connections._connections.connections['default'].close()  # because it might be opened and we can't check
> connections._connections.connections['default'].open()
> # actual code for sending messages
> ...
> 
> connections._connections.connections['default'].close()
> ```
> 
> Proper solution is IMO add option to disable connection caching when using long running threads.



> I changed it later, works on production without problems:
> 
> ```python
> try:
>     connections._connections.connections['default'].close()
>     connections._connections.connections['default'].open()
> except AttributeError:
>     pass
> ```
> 
> Don't judge me :)
> 
> I will try to find some time to make pull request with disabling connection caching based on settings. It will solve all of the problems.

Any update on this thing, I am using post_office for my one project,
````python
EMAIL_BACKEND = 'post_office.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_PORT = os.getenv('EMAIL_PORT')


POST_OFFICE = {
    'THREADS_PER_PROCESS' : 10,
    'SENDING_ORDER': ['created'],
    'LOG_LEVEL' : 2,
}

POST_OFFICE_CACHE = False
````
My requirement is to send / queue 300 emails. I have done that using mail.send() method without mentioning any priority. The library is able to send about 130 mails but then it failed to send emails with errors:
first few with `450, b'4.7.1 Error: too much mail from`
then `Connection unexpectedly closed`
and at last few mails with `please run connect() first`

I am using a cronjob to send queued mails. Deployed the application with gunicorn 
@grapo, any update on this?

**Comment by Aameer** [comment]
Hey guys, any update on this issue? we have been using `django-post_office` for a while and have been waiting for a fix for this. We had set up a cron which essentially closes and opens the connection as discussed above. This cron would essentially retry any failed emails. 
In a distributed system where local attachments (which are generated dynamically) have to be sent with the email this cron would have to be deployed on all servers otherwise some retries would fail because attachments are on different servers. Once we have crons on all servers that creates another issue in which at times multipe copies of the same email are being sent as the cron is running on different servers. For now I am considering changing the priority for this email ( which maynot be possible is some use cases)  but I believe unless this root cause is fixed it will manifest itself in some other form. Thanks

**Comment by Mogost** [comment]
@jrief, could you take a look at this issue?

**Comment by jrief** [comment]
@Mogost This might get solved after pull request #302 is merged. Currently there is only one attempt to deliver an email to the SMTP server.

You may help out on this pull request by reviewing it and/or fixing its annotations.

**Comment by oesah** [comment]
So for us ALL mails now fail since we Upgraded to the latest Version of Post Office a week ago. We get the following error:

Exception: `SMTPServerDisconnected`
Trace: `please run connect() first`

This is very critical, please help!

**Comment by jrief** [comment]
@oesah django-post_office does not handle the low level connectivity to the remote SMTP-relay. This is part of Django's `smtplib` implementation. Please first try to send an email using
```bash
manage.py sendtestemail john@example.com
```

to check if your settings are correct.

**Comment by oesah** [comment]
@jrief Yeah, this works. So I also hooked up celery. The first time it tries to send it (`NOW` as priority), it fails. Then I put them back into the queue, and celery is able to send them correctly. Any idea why this could be the case? I will try to set the priority to something other than `NOW` and let celery handle it, but still confused why this happened all of the sudden.

**Comment by jrief** [comment]
Don't use priority `NOW`, especially not together with Celery. It thwards the main reason for using post_office, namely its asynchronously.
With Celery, emails are sent immediately after they have been queued, but by another task.

**Comment by juancrescente** [comment]
I got the same issue without celery. I have to restart gunicorn to make it work again

**Comment by jrief** [comment]
@mihalikv 
you should not create emails using a Celery task.

```
@task(name='send_registration_mail')
def send_registration_mail():
    ...
```

instead you should just send an email using `mail.send(...)` directly, without doing it asynchronously. Celery will take care of delivering queued emails.

**Comment by pupattan** [comment]
I am using mail.send(...) still the same issue with uwsgi

**Comment by WoLpH** [comment]
I can confirm the issue when running Gunicorn without Celery. The `NOW` priority seems very much broken

**Comment by weimens** [comment]
Anyone here that could confirm that my pull request #352 works for them too? It works for me in production for nearly an month now. Though I am on an version that is integrated in seafile. As @xiez mentioned, for seafile this bug was fixed in https://github.com/haiwen/django-post_office/commit/2312cf240363721f737b5ac8eb86ab8cb255938f, but nobody made an pull request to fix this issue in upstream. I would appreciate it when the pull request gets merged, so that this problem those not recur in seafile.

**Comment by WoLpH** [comment]
It doesn't appear to work for me weimens, I'm still seeing the issue unfortunately.

I do think it might be less often though
