### ISSUE TITLE
Celery Task triggered by signal is not thread safe: Multiple E-Mails sent!

### ISSUE THREAD

**Issue by ErrorInPersona** [ui/django-post_office#326]
Let´s say we have a task running with multiple threads. Within each single process of this task, there might be sent a mail with post-offices mail.send() method.

Now the signal is triggered:

```
from django.dispatch import Signal

email_queued = Signal(providing_args=['emails'])
```

It calls this task here:

```
def queued_mail_handler(sender, **kwargs):
        """
        To be called by post_office.signals.email_queued.send()
        """
        send_queued_mail.delay()
```
Every task will call 'send_queued_mail' async.

The problem is, that the method get_queued does not lock the selected items on the database, where it should use djangos **select_for_update** method.

The actual behavior leads to **a single mail be sent dozens of times** until the database has the mail marked as sent.

At the moment I cant even disable the signal-handling.

Could you fix this or may I send a PR?

**Comment by jrief** [comment]
@ErrorInPersona Thanks for informing. This indeed seems to be a major flaw. I fixed it in PR #327.
Please retry with that branch, tell me if it works for you and I will release a new version ASAP.

**Comment by ErrorInPersona** [comment]
> @ErrorInPersona Thanks for informing. This indeed seems to be a major flaw. I fixed it in PR #327.
> Please retry with that branch, tell me if it works for you and I will release a new version ASAP.

@jrief thanks a lot for your swift response! Your commit does not fix the problem. I guess its a procedural problem. We here select the mails, but we don´t immediatley save them as "sent" here. In our test this leads to no effect. Because it will simply be reselected after the log is gone and before the row was saved as sent?

**Comment by aritas1** [comment]
the select_for_update() lock will trigger an exception in line 283, after the mail was send...
https://github.com/ui/django-post_office/blob/ab813df4bf2c3471bb5f79466adfb7a5af6c3e10/post_office/mail.py#L283

worst case you will dupicate the mails by the number of workers

for a good enough "not guaranteed to fail" test, you can try this:

```
import threading
import time
from django.test import TestCase, override_settings
from post_office import mail
from django.core import mail as mail_core


class TestPostOffice(TestCase):

    @override_settings(EMAIL_BACKEND='django.core.mail.backends.locmem.EmailBackend')
    @override_settings(CELERY_TASK_ALWAYS_EAGER=True)
    def test_try_post_office_thread_safe(self):
        self.assertEqual(len(mail_core.outbox), 0)

        def send_mail(number, sleep=60):
            time.sleep(sleep)
            mail.send(
                'recipient' + str(number) + '@example.com',
                'from@example.com',
                subject='mail' + str(number),
            )

        # create multiple threads
        t1 = threading.Thread(target=send_mail, args=(1, 0))
        t2 = threading.Thread(target=send_mail, args=(2, 0))
        t3 = threading.Thread(target=send_mail, args=(3, 0))

        # starting all the send with no delay: MAY trigger multitasking (not guaranteed!)
        t1.start()
        t2.start()
        t3.start()

        # wait for the tasks to end
        t1.join()
        t2.join()
        t3.join()

        # send all emails, pre 3.4.0 behavior
        # this will not hurt with 3.4.0+ if the mails are send
        mail.send_queued()

        self.assertEqual(len(mail_core.outbox), 3)
```

**Comment by fadedDexofan** [comment]
@jrief @ErrorInPersona @aritas1 check this pls https://github.com/fadedDexofan/django-post_office/commit/e1e6c849126119b582a53ed0c31dae4ef4fea9ba

**Comment by selwin** [comment]
See my comment [here](https://github.com/ui/django-post_office/pull/338#issuecomment-719905372). The TLDR is that the celery tasks should acquire a lock before sending emails.

The bug is on how celery tasks are being implemented. If you don't use celery tasks, you should be fine.

**Comment by selwin** [comment]
Since some people have been clamoring for the new features, I'm releasing 3.5.0. We can make a minor release to address this issue when a PR is ready.
