### ISSUE TITLE
Deprecation warnings for Django 1.8

### ISSUE THREAD

**Issue by andrewyager** [ui/django-post_office#97]
There are currently a number of deprecation warnings generated when using post_office with Django 1.8.

    ...lib/python2.7site-packages/post_office/settings.py:35: RemovedInDjango19Warning: 'get_cache' is deprecated in favor of 'caches'.
      return get_cache("default")

    ...lib/python2.7/site-packages/post_office/models.py:28: RemovedInDjango19Warning: Model class post_office.models.Email doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
      class Email(models.Model):

    ...lib/python2.7/site-packages/post_office/models.py:147: RemovedInDjango19Warning: Model class post_office.models.Log doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
      class Log(models.Model):

    ...lib/python2.7/site-packages/post_office/models.py:164: RemovedInDjango19Warning: Model class post_office.models.EmailTemplate doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
      class EmailTemplate(models.Model):

    ...lib/python2.7/site-packages/post_office/models.py:200: RemovedInDjango19Warning: Model class post_office.models.Attachment doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.

**Comment by selwin** [comment]
Thanks for the report, mind opening a PR for these? :)

**Comment by andrewyager** [comment]
Sure. How? :) (excuse ignorance… feel free to RTFM me!)

**Comment by selwin** [comment]
Fork this repository, commit your changes and submit a pull request so I can review the changes :)

**Comment by Ivaylo-Bachvarov** [comment]
Yea, same problem here. We are trying to give it a fix but with no success so far.

**Comment by selwin** [comment]
The deprecation warnings should already be fixed in the master branch. Please give it a spin and let me know if there's more.

**Comment by tamakisquare** [comment]
@selwin - I am on v2.0 with Django 1.8.2 and I am still getting a deprecation warning (detail below)

> /.../python3.4/site-packages/post_office/models.py:220: RemovedInDjango19Warning: Model class post_office.models.Attachment doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.

**Comment by selwin** [comment]
I added AppConfig for Django 1.8 on this file https://github.com/ui/django-post_office/blob/master/post_office/apps.py so I'm actually not sure why we're still getting that warning. A PR to fix this issue will be great.

**Comment by tamakisquare** [comment]
@selwin - The culprit is the imports found in https://github.com/ui/django-post_office/blob/master/post_office/__init__.py. According to [How applications are loaded](https://docs.djangoproject.com/en/1.8/ref/applications/#how-applications-are-loaded) in the official docs,  the app shouldn't be importing any models, even indirectly, in the `__init__.py`.

Removing those imports makes that *RemovedInDjango19Warning* goes away. My question to you is are those imports needed at all.

**Comment by selwin** [comment]
If we do, it's probably only for minor syntactic convenience. A PR to fix this would be welcome :)
